routing:

  admin_testimonial_list:
    path: ^\/admin\/testimonial\/list\/?$
    isSecure: 1
    i18n: 1
    controller: testimonial/backend/testimonial_list
  admin_testimonial_edit:
    path: ^\/admin\/testimonial\/edit\/(\d+)\/?$
    isSecure: 1
    i18n: 1
    controller: testimonial/backend/testimonial_edit
  admin_testimonial_create:
    path: ^\/admin\/testimonial\/create\/?$
    isSecure: 1
    i18n: 1
    controller: testimonial/backend/testimonial_create
  admin_testimonial_delete:
    path: ^\/admin\/testimonial\/delete\/(\d+)\/?$
    isSecure: 1
    i18n: 0
    controller: testimonial/backend/testimonial_delete