country:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    name: VARCHAR(31) NOT NULL
    image: VARCHAR(255)
    content: TEXT
  form:
    fields:
      name:
        widget: text
        widget_conf:
          required: 1
      image:
        widget: image
        widget_conf:
          required: 1
          multiple: 0
          upload_dir: files/country
          transform:
            dimension: 300x244
      content:
        widget: textarea
        widget_conf:
          required: 1
          wysiwyg: 1
    names:
      en: Country
      zh: 留学国家